### PR TITLE
fix elixir compatibility

### PR DESCRIPTION
**Pull request by munjalpatel**

### CODE REVIEW

**Comment by munjalpatel** [comment]
@tessi here is why tests for `OTP 25.2 / x` are failing.

Order matter when we instantiate dependent links.
If `Module B` depends on `Module A`, we need to instantiate `Module A` _before_ `Module B`

So, as in the unit test, we are passing in `utils` _before_ `calculator` since calculator depends on utils.
```ex
links = %{
    utils: %{bytes: utils_wasm},
    calculator: %{bytes: calculator_wasm}
}
```

This order is preserved in Rust for `OTP 26.2 / x` where tests are passing.
image

However, the order is not preserved in Rust for `OTP 25.2 / x` and hence, the tests are failing since `calculator` module can't find `utils` upon instantiation.
image

@scrogson any ideas why the order of items is not preserved in the Rust vector for `OTP 25.2`?

**Comment by tessi** [comment]
uhhh good find! OTP 26 actually had this covered in their release notes:

> Some map operations have been optimized by changing the internal sort order of atom keys. This changes the (undocumented) order of how atom keys in small maps are printed and returned. The new order is unpredictable and may change between different invocations of the Erlang VM.

https://www.erlang.org/news/164#maps

Rendering maps are unpredictable in their order. Which is totally how maps are defined, so fair call from Elixir. If we can't get around ordering in linked Wasm modules, we need to use some other solution.

I thought about keyword lists instead (since they are just lists with map-like syntax), [but they also don't promise any ordering](https://hexdocs.pm/elixir/1.12/Keyword.html#module-duplicate-keys-and-ordering). Well, at least not when manipulating them - but constructing them should keep the order intact 🤔 (it's just a list of 2-tuples after all). In that sense: we could switch the implementation to kw lists. What do you think? or just make it proper lists of maps again?

In any way (kw lists, or lists of maps), we have the duplicated names problem back. I'm afraid we need a nice error when instantiating a module with duplicated links or need to filter links so that only the first name is taken (similar how `Keyword.get([foo: 1, foo: 2], :foo)` would only return `1`).

**Comment by tessi** [comment]
wait! this problem only comes because we have a chain of links where ordering is important. So actually we don't want to order links properly, because (with many, many linked modules) this would be a mess to implement and maintain manually. We actually want nested links 🙈 

like

```elixir
links = %{
  calculator: %{
    bytes: calculator_wasm,
    links: %{utils: %{bytes: utils_wasm}}
  }
}
```

Right? we could then flatten this nested map and reverse it so that the most deeply nested dependency gets loaded first. (this doesn't solve for duplicated names, especially not if the _same_ name points to a _different_ module - but the initial solution on the PR also doesn't solve that edge case - so, fair enough, maybe! :D)

**Comment by munjalpatel** [comment]
> wait! this problem only comes because we have nested links where ordering is important. I think we actually don't want to order links in a flat list, because that is a faulty and wrong abstraction of the nested nature of the example you provided (with many, many nested linked modules this would be a mess to implement and maintain manually as a user of wasmex).
> 
> We actually want proper nested links 🙈 - like:
> 
> ```elixir
> links = %{
>   calculator: %{
>     bytes: calculator_wasm,
>     links: %{utils: %{bytes: utils_wasm}}
>   }
> }
> ```
> 
> Right? we could then flatten this nested map and reverse it so that the most deeply nested dependency gets loaded first. (this doesn't solve for duplicated names, especially not if the _same_ name points to a _different_ module - but the initial solution on the PR also doesn't solve that edge case - so, fair enough, maybe! :D)

That's what I was thinking as well. It's a lot more clear API.

**Comment by munjalpatel** [comment]
@tessi supporting child links also mean we will be actually solving dependency issue (though we will still link all modules directly to the main in Rust). But we will have to parse and compile through the tree for all `links` in the map.

**Comment by tessi** [comment]
@munjalpatel true that we need still only have a flat list in rust. Is there a way with wasmtime to solve this proper? Could we give the nested list to rust and somehow make it work? (I actually don't know, but if you also don't know I could dig in a bit)

**Comment by munjalpatel** [comment]
> @munjalpatel true that we need still only have a flat list in rust. Is there a way with wasmtime to solve this proper? Could we give the nested list to rust and somehow make it work? (I actually don't know, but if you also don't know I could dig in a bit)

I am not sure about that either.

**Comment by scrogson** [comment]
Hey folks! Sorry, I'm trying to get up-to-speed on this project and understand what problem is being solved.

> @scrogson any ideas why the order of items is not preserved in the Rust vector for `OTP 25.2`?

I'm not sure, this is the first time I've seen this type of behaviour. The example in your comment is a little confusing given that you're using a map for links, but the current implementation is a list of maps isn't it?

@tessi in this currently implementation (`Vec<LinkedModule>`), map key ordering doesn't matter as this is a list of maps.

As for nested linking, from my limited understanding of how any of the WASM module linking works, it does seem that the structure would need to be something like:

```rust
#[derive(NifMap)]
pub struct LinkedModule {
    pub name: String,
    pub module_resource: ResourceArc<ModuleResource>,
    pub links: Box<Vec<LinkedModule>>
}
```

Does that seem correct?

**Comment by scrogson** [comment]
Oh, after a further look, I think I realize that we were talking about different levels. I see now that at the higher level in the Elixir code, we're using a map which is later converted to a list of maps before calling the NIF.

So yes, unstable map key ordering was the issue. Looks like @munjalpatel got it sorted. 👍

**Pull request merged**
